### ISSUE TITLE
A theme example?

### ISSUE THREAD

**Issue by int-ua** [VITObelgium/drupal-boilerplate#1]
I'm trying to [i18ze the `estore` theme](https://www.drupal.org/project/estore/issues/3175871) and having trouble finding a good example. Looks like I'm not the only one: https://drupal.stackexchange.com/q/193919/7177

I've tried to add `langcode: en` in the end of `estore/config/install/estore.settings.yml`, `mapping` to `estore/config/schema/estore.schema.yml`:
```yml
  mapping:
    copyright_text:
      type: label
    header_location:
      type: label
    header_shop_opens:
      type: label
```
But it did not work it seems.
